apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes
spec:
  selector:
    matchLabels:
      app: springboot-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      containers:
        - name: spring-boot
          image: kaushal1983/docker-repo_self:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081