apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes-service
spec:
  ports:
    - protocol: "TCP"
      port: 8081        # The port inside the cluster
      targetPort: 8082  # The port exposed by the service
  type: NodePort        # Type of service
  selector: spring-boot